version: 0.2 # 파일 형식 버전(현재 0.2 사용).

env:
  variables:               # 명시적 환경 변수
    S3_BUCKET: "sili-cdn-deployment"
    DISTRIBUTION_ID: "E2LSO4LIHSWRHH"

phases:
  install: # install
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - cd frontend                # frontend 디렉토리로 이동
      - npm install
  build: # 프로젝트 빌드 명령 실행(`npm run build`)
    commands:
      - echo "Building the project..."
      - npm run build
  post_build: # 빌드 후 S3에 파일을 업로드.
    commands:
      - echo "Syncing build output to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
artifacts: # 빌드 결과물을 저장 및 배포할 파일 패턴 정의.
  files:
    - '**/*'
cache:
  paths:
    - frontend/node_modules/**/*
