version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.monolithic.nextjs
    ports:
      - "80:80"
    depends_on:
      - nextjs

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.monolithic.nginx
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production