version: 0.2
env:
  variables:               # 명시적 환경 변수
    ECS_CLUSTER_NAME: "sili-cdn-deployment"
    SERVICE_NEXTJS_NAME: "E2LSO4LIHSWRHH"
    SERVICE_NGINX_NAME: "E2LSO4LIHSWRHH"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - cd next-frontend
      - npm run build
      - npx next export
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Building Next.js image...
      - docker build -f Dockerfile.nextjs -t $SERVICE_NEXTJS_NAME .
      - docker tag $SERVICE_NEXTJS_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SERVICE_NEXTJS_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SERVICE_NEXTJS_NAME:latest
      - echo Building Nginx image...
      - docker build -f Dockerfile.nginx -t $SERVICE_NGINX_NAME .
      - docker tag $SERVICE_NGINX_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SERVICE_NGINX_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SERVICE_NGINX_NAME:latest
      - echo Updating Next.js ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $SERVICE_NEXTJS_NAME --force-new-deployment
      - echo Updating Nginx ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service  $SERVICE_NGINX_NAME --force-new-deployment
artifacts:
  files:
    - '**/*'